#pragma config(Sensor, in1,    ,               sensorPotentiometer)
#pragma config(Sensor, in2,    ,               sensorReflection)
#pragma config(Sensor, dgtl1,  ,               sensorSONAR_cm)
#pragma config(Motor,  port1,           Leftdrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port7,           flashy,        tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armbase,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightdrive,    tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{ while (1==1)



motor(port1)= -vexRT[Ch2];
		motor(port10)= vexRT[Ch3];



	if(vexRT[Btn6D] == 1) // if button 6d is pressed ......
	{

		motor(port8)= -127;

}
else if(vexRT[Btn6U] ==1) // if button 6u is pressed instead ...
	{

		motor(port8)= 127;

	}
		else // if nothing is pushed...
	{

		motor(port8)= 0;
	}
	if(vexRT[Btn5D] == 1) // if button 6d is pressed ......
	{

		motor(port9)= -127;

}
else if(vexRT[Btn5U] ==1) // if button 6u is pressed instead ...
	{

		motor(port9)= 127;

	}
		else // if nothing is pushed...
	{

		motor(port9)= 0;
	}}
