#pragma config(Sensor, in2,    ,               sensorReflection)
#pragma config(Sensor, in3,    ,               sensorPotentiometer)
#pragma config(Motor,  port7,            ,             tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{while (1==1)












	if (SensorValue (in3) >0)
	{
		if(vexRT[Btn6D] == 1) // if button 6d is pressed ......
	{

		motor(port9)= -127;

}
else if(vexRT[Btn6U] ==1) // if button 6u is pressed instead ...
	{

		motor(port9)= 127;

	}
		else // if nothing is pushed...
	{

		motor(port9)= 0;
	}

	if (SensorValue( in3) <=0)
	{ motor(port9) = 127;
		waitInMilliseconds(500);
	}





{
	if (SensorValue(in2) >300)
{
	motor (port7) =127;

}
if (SensorValue (in2) <300)
{
	motor(port7)= 0;
}}}}
