#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  wait1Msec(2000);  //Two second Delay

  SensorValue[rightEncoder] = 0;  //Clear the right encoder value
  SensorValue[leftEncoder] = 0;   //Clear the left encoder value

  //While the encoders have spun less than 3 rotations...
  while(SensorValue[rightEncoder] < 1080)
  {
    //Move Forward
    motor[rightMotor] = 63;
    motor[leftMotor] = 63;
  }


  //Stop for half a second
  motor[rightMotor] = 0;
  motor[leftMotor] = 0;
  wait1Msec(500);


  SensorValue[rightEncoder] = 0;  //Clear the right encoder value
  SensorValue[leftEncoder] = 0;   //Clear the left encoder value

  //While the right encoder has spun less than 1 rotation...
  while(SensorValue[leftEncoder] < 360)
  {
    //Turn Left
    motor[rightMotor] = -63;
    motor[leftMotor] = 63;
  }}
