#pragma config(Sensor, dgtl2,  ,               sensorTouch)
#pragma config(Motor,  port10,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

			untilBump(dgtl2);
	motor(port10) = -80 ;

	waitInMilliseconds(1000);
	untilBump(dgtl2);
	motor(port10) = 0 ;

	waitInMilliseconds(1);


}
