#pragma config(Motor,  port1,           frontrightdriver, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontleftdriver, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           armright,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           armleft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftright,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftleft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           backrightdriver, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          backleftdriver, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard           !!*///*

task main()
{ while (1==1)
	{
		motor(port1)= -vexRT[Ch2]; // port 1 is the front right driver
		motor(port2)= -vexRT[Ch3]; // port 2 is the back  right driver
		motor(port9)=  vexRT[Ch2]; // port 9 is the front left  driver
		motor(port10)= vexRT[Ch3];// port 10 is the back  left driver

	if(vexRT[Btn6U] == 1) // if button 6u is pressed lift goes up
	{
		motor(port3)= 80;
		motor(port4)= -80; // ... raise the arm

		}
	else if(vexRT[Btn6D] ==1) // if button 6d is pressed lift goes down
	{
		motor(port3)= -80;
		motor(port4)= 80; // ... lower the arm

	}
	else // if nothing is pushed...
	{
		motor(port3)= 0;
		motor(port4)= 0;// ...stop the arm

	}
	if (vexRT[Btn8U] ==1) //if button 8r is pressed elevator goes up
	{
		motor(port7) = 80;
		motor(port8) = -80; // .. raise the elevator
	}
	else if (vexRT[Btn8D] ==1) // if button 8d is pressed elevator goes down
	{
		motor(port7) = -80;
		motor(port8) = 80; // ...lower the elevator
	}
	else // if nothing is pushed...
	{
		motor(port7) = 0;
		motor(port8) = 0;  //... elevator stops
	}
		if(vexRT[Btn5U] == 1) // if button 5u is close claw
	{
		motor(port5)= 80;

	}
	else if(vexRT[Btn5D] ==1) // if button 5d is pressed open claw
	{
		motor(port5)= -80;

	}
	else // if nothing is pushed...
	{
		motor(port5)= 0; // nothn happens
}
}
}
