
#pragma config(Motor,  port1,           rightdriver,   tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           outleft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           inleft,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           outright,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           inright,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightlift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftlift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftleft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           clawfront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftdriver,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{ while (1==1)
	{
		motor(port1)= -vexRT[Ch2]; // port 1 is the right driver,front wheels
		motor(port10)= vexRT[Ch3];// port 10 is the left driver,front wheels
		motor(port3)= vexRT[Ch3]; // port 1 is the leftdriver
		motor(port5)= vexRT[Ch2];// port 10 is the right driver


	if(vexRT[Btn6U] == 1) // if button 6u is pressed lift goes up
	{
		motor(port2)= -127;
		motor(port2)= 127;
		motor(port4)= 127;
		motor(port4)= -127;	//......raise the arm
	}
	else if(vexRT[Btn6D] ==1) // if button 6d is pressed lift goes down
	{
		motor(port2)= 127;
		motor(port2)= -127;
		motor(port4)= -127;
		motor(port4)= 127; // ... lower the arm
	}
	else // if nothing is pushed...
	{
		motor(port2)= 0;
		motor(port2)= 0;//im not writing any code im just extremely depressed
		motor(port4)= 0;
		motor(port4)= 0; // ...stop the arm
	}
	if (vexRT[Btn8R] ==1) //if button 8r is pressed elevator goes up
	{
		motor(port6) = 127;
		motor(port7) = -127; // .. raise the elevator
	}
	else if (vexRT[Btn8D] ==1) // if button 8d is pressed elevator goes down
	{
		motor(port6) = -127;
		motor(port7) = 127; // ...lower the elevator
	}
	else // if nothing is pushed...
	{
		motor(port6) = 0;
		motor(port7) = 0;  //... elevator stops
	}
		if(vexRT[Btn5U] == 1) // if button 5u is close claw
	{
		motor(port9)= 127;

	}
	else if(vexRT[Btn5D] ==1) // if button 5d is pressed open claw
	{
		motor(port9)= -127;

	}
	else // if nothing is pushed...
	{
		motor(port9)= 0; // nothn happens
}
}
}
