#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
untilBump(dgtl1);
motor (port2)=127;
motor (port3)=127;
untilBump(dgtl1);
motor (port2)=0;
motor (port3)=0;
untilBump(dgtl1);
motor (port2)=127;
motor (port3)=127;
untilBump(dgtl1);
motor (port2)=0;
motor (port3)=0;
untilBump(dgtl1);
motor (port2)=127;
motor (port3)=127;
untilBump(dgtl1);
motor (port2)=0;
motor (port3)=0;
untilBump(dgtl1);
motor (port2)=127;
motor (port3)=127;
untilBump(dgtl1);
motor (port2)=0;
motor (port3)=0;
untilBump(dgtl1);
motor (port2)=127;
motor (port3)=127;
untilBump(dgtl1);
motor (port2)=0;
motor (port3)=0;
}
