#pragma config(Sensor, dgtl7,  solenoid,            sensorDigitalOut)
//*!!Code automatically generated by ‘ROBOTC’ configuration wizard               !!*//

task main()
{
while(true)
{
	{
SensorValue[solenoid] = 1;  // …activate the solenoid.
waitInMilliseconds(500);
SensorValue[solenoid] = 0;  // ..deactivate the solenoid.
waitInMilliseconds(1000);
}
}}
