#pragma config(Sensor, in1,    ,               sensorPotentiometer)
#pragma config(Sensor, in2,    ,               sensorReflection)
#pragma config(Sensor, dgtl1,  ,               sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  ,               sensorTouch)
#pragma config(Sensor, dgtl4,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  ,               sensorQuadEncoder)
#pragma config(Motor,  port1,           rightdriver,   tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           leftdriver,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           BottomRight,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           Topright,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{ while (1==1)
	{
		{motor(port1)= -vexRT[Ch2]; // port 9 is the right driver
		motor(port10)= vexRT[Ch3];// port 10 is the left driver
}


	if(vexRT[Btn6D] == 1) // if button 6d is pressed ......
	{
		motor(port8)= 127;

			//......raise the arm
	}
	else if(vexRT[Btn6U] ==1) // if button 6u is pressed instead ...
	{
		motor(port8)= -127;

		 // ... lower the arm
	}
	else // if nothing is pushed...
	{
		motor(port8)= 0;

		 // ...stop the arm //... stop the scoop arm
	}
}
}
//untilPotentiometerGreaterThan(2048, in2);
//untilEncoderCounts (480,dgtl3);
