#pragma config(Motor,  port1,           rightdriver,   tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           leftdriver,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rightdrivertop, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           leftdrivertop, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           lift,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           clawbase,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           clawbase,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           arm,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           liftreversed,  tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{ while (1==1)
	{
		motor(port1)= -vexRT[Ch2]; // port 9 is the right driver
		motor(port3)= -vexRT[Ch2];
		motor(port2)= vexRT[Ch3];// port 10 is the left driver
	motor(port4)= vexRT[Ch3];
	if(vexRT[Btn6D] == 1) // if button 6d is pressed ......
	{

		motor(port5)= -127;
		motor(port9)= 127;
			//......raise the arm
	}
	else if(vexRT[Btn6U] ==1) // if button 6u is pressed instead ...
	{

		motor(port5)= 127;
		motor(port9)= -127;
	 // ... lower the arm
	}
	else // if nothing is pushed...
	{

		motor(port5)= 0;
		motor(port9)= 0;
		 // ...stop the arm
	}
	if (vexRT[Btn5D] ==1) //if button 5d is pressed...
	{
		motor(port6) = 127;
		motor(port7) = -127; // .. raise the scoop arm
	}
	else if (vexRT[Btn5U] ==1) // if button 5u is pressed instead...
	{
		motor(port6) = -127;
		motor(port7) = 127; // ...lower the scoop arm
	}
	else // if nothing is pushed...
	{
		motor(port6) = 0;
		motor(port7) = 0;  //... stop the scoop arm
	}
		if(vexRT[Btn7D] == 1) // if button 6d is pressed ......
	{

		motor(port8)= -127;
			//......raise the arm
	}
	else if(vexRT[Btn7U] ==1) // if button 6u is pressed instead ...
	{

		motor(port8)= 127;
	 // ... lower the arm
	}
	else // if nothing is pushed...
	{

		motor(port8)= 0;
}
}
}
